import { Card, EntityState, Relic, Consumable, Task, ShopUpgrade } from './types';

export const TERMINOLOGY = {
  HP: '系统完整度 (Integrity)',
  ENERGY: '核心算力 (Core)',
  DRAW_PILE: '背包系统 (Backpack)',
  DISCARD_PILE: '回收站 (Recycle)',
  END_TURN: '执行指令 (Execute)',
};

export const POKEMON_DB: Omit<EntityState, 'hp' | 'shield' | 'energy' | 'statusEffects' | 'intent'>[] = [
  {
    id: 'pikachu',
    name: '皮卡丘 (Pikachu)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    maxHp: 100,
    maxEnergy: 3,
    color: '#facc15',
    neonClass: 'neon-yellow',
    bgGradient: 'from-yellow-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
    evolutionLevel: 10,
    evolvesTo: 'raichu',
  },
  {
    id: 'raichu',
    name: '雷丘 (Raichu)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png',
    maxHp: 140,
    maxEnergy: 4,
    color: '#facc15',
    neonClass: 'neon-yellow',
    bgGradient: 'from-yellow-900/40 to-black',
    level: 10,
    xp: 0,
    nextXp: 250,
  },
  {
    id: 'charmander',
    name: '小火龙 (Charmander)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    maxHp: 90,
    maxEnergy: 3,
    color: '#f97316',
    neonClass: 'neon-orange',
    bgGradient: 'from-orange-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
    evolutionLevel: 10,
    evolvesTo: 'charmeleon',
  },
  {
    id: 'charmeleon',
    name: '火恐龙 (Charmeleon)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png',
    maxHp: 120,
    maxEnergy: 3,
    color: '#f97316',
    neonClass: 'neon-orange',
    bgGradient: 'from-orange-900/40 to-black',
    level: 10,
    xp: 0,
    nextXp: 250,
    evolutionLevel: 20,
    evolvesTo: 'charizard',
  },
  {
    id: 'charizard',
    name: '喷火龙 (Charizard)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    maxHp: 160,
    maxEnergy: 4,
    color: '#f97316',
    neonClass: 'neon-orange',
    bgGradient: 'from-orange-900/40 to-black',
    level: 20,
    xp: 0,
    nextXp: 500,
  },
  {
    id: 'squirtle',
    name: '杰尼龟 (Squirtle)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
    maxHp: 110,
    maxEnergy: 3,
    color: '#3b82f6',
    neonClass: 'neon-blue',
    bgGradient: 'from-blue-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
    evolutionLevel: 10,
    evolvesTo: 'wartortle',
  },
  {
    id: 'wartortle',
    name: '卡咪龟 (Wartortle)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png',
    maxHp: 140,
    maxEnergy: 3,
    color: '#3b82f6',
    neonClass: 'neon-blue',
    bgGradient: 'from-blue-900/40 to-black',
    level: 10,
    xp: 0,
    nextXp: 250,
    evolutionLevel: 20,
    evolvesTo: 'blastoise',
  },
  {
    id: 'blastoise',
    name: '水箭龟 (Blastoise)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
    maxHp: 180,
    maxEnergy: 4,
    color: '#3b82f6',
    neonClass: 'neon-blue',
    bgGradient: 'from-blue-900/40 to-black',
    level: 20,
    xp: 0,
    nextXp: 500,
  },
  {
    id: 'bulbasaur',
    name: '妙蛙种子 (Bulbasaur)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
    maxHp: 100,
    maxEnergy: 3,
    color: '#22c55e',
    neonClass: 'neon-green',
    bgGradient: 'from-green-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
    evolutionLevel: 10,
    evolvesTo: 'ivysaur',
  },
  {
    id: 'ivysaur',
    name: '妙蛙草 (Ivysaur)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png',
    maxHp: 130,
    maxEnergy: 3,
    color: '#22c55e',
    neonClass: 'neon-green',
    bgGradient: 'from-green-900/40 to-black',
    level: 10,
    xp: 0,
    nextXp: 250,
    evolutionLevel: 20,
    evolvesTo: 'venusaur',
  },
  {
    id: 'venusaur',
    name: '妙蛙花 (Venusaur)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    maxHp: 170,
    maxEnergy: 4,
    color: '#22c55e',
    neonClass: 'neon-green',
    bgGradient: 'from-green-900/40 to-black',
    level: 20,
    xp: 0,
    nextXp: 500,
  },
  {
    id: 'mewtwo',
    name: '超梦 (Mewtwo)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
    maxHp: 120,
    maxEnergy: 3,
    color: '#c084fc',
    neonClass: 'neon-purple',
    bgGradient: 'from-purple-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
  },
  {
    id: 'tyranitar',
    name: '班基拉斯 (Tyranitar)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png',
    maxHp: 150,
    maxEnergy: 3,
    color: '#4ade80',
    neonClass: 'neon-green',
    bgGradient: 'from-green-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
  },
  {
    id: 'lucario',
    name: '路卡利欧 (Lucario)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png',
    maxHp: 110,
    maxEnergy: 4,
    color: '#38bdf8',
    neonClass: 'neon-blue',
    bgGradient: 'from-blue-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
  },
  {
    id: 'gastly',
    name: '鬼斯 (Gastly)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png',
    maxHp: 70,
    maxEnergy: 3,
    color: '#a855f7',
    neonClass: 'neon-purple',
    bgGradient: 'from-purple-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
    evolutionLevel: 10,
    evolvesTo: 'haunter',
  },
  {
    id: 'haunter',
    name: '鬼斯通 (Haunter)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png',
    maxHp: 100,
    maxEnergy: 3,
    color: '#a855f7',
    neonClass: 'neon-purple',
    bgGradient: 'from-purple-900/40 to-black',
    level: 10,
    xp: 0,
    nextXp: 250,
    evolutionLevel: 20,
    evolvesTo: 'gengar',
  },
  {
    id: 'gengar',
    name: '耿鬼 (Gengar)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
    maxHp: 140,
    maxEnergy: 4,
    color: '#a855f7',
    neonClass: 'neon-purple',
    bgGradient: 'from-purple-900/40 to-black',
    level: 20,
    xp: 0,
    nextXp: 500,
  },
  {
    id: 'dratini',
    name: '迷你龙 (Dratini)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png',
    maxHp: 80,
    maxEnergy: 3,
    color: '#fbbf24',
    neonClass: 'neon-yellow',
    bgGradient: 'from-yellow-900/40 to-black',
    level: 1,
    xp: 0,
    nextXp: 100,
    evolutionLevel: 10,
    evolvesTo: 'dragonair',
  },
  {
    id: 'dragonair',
    name: '哈克龙 (Dragonair)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png',
    maxHp: 110,
    maxEnergy: 3,
    color: '#fbbf24',
    neonClass: 'neon-yellow',
    bgGradient: 'from-yellow-900/40 to-black',
    level: 10,
    xp: 0,
    nextXp: 250,
    evolutionLevel: 20,
    evolvesTo: 'dragonite',
  },
  {
    id: 'dragonite',
    name: '快龙 (Dragonite)',
    img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png',
    maxHp: 160,
    maxEnergy: 4,
    color: '#fbbf24',
    neonClass: 'neon-yellow',
    bgGradient: 'from-yellow-900/40 to-black',
    level: 20,
    xp: 0,
    nextXp: 500,
  },
];

export const INITIAL_DECKS: Record<string, Omit<Card, 'uid'>[]> = {
  pikachu: [
    { id: 'p1', name: '电击.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, desc: '造成 8 点伤害。获得 1 层 [电荷]', vfx: 'electric', selfStatusEffect: { type: 'CHARGE', value: 1 } },
    { id: 'p1', name: '电击.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, desc: '造成 8 点伤害。获得 1 层 [电荷]', vfx: 'electric', selfStatusEffect: { type: 'CHARGE', value: 1 } },
    { id: 'p1', name: '电击.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, desc: '造成 8 点伤害。获得 1 层 [电荷]', vfx: 'electric', selfStatusEffect: { type: 'CHARGE', value: 1 } },
    { id: 'p1', name: '电击.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, desc: '造成 8 点伤害。获得 1 层 [电荷]', vfx: 'electric', selfStatusEffect: { type: 'CHARGE', value: 1 } },
    { id: 'p2', name: '电光一闪.cmd', type: 'ATTACK', rarity: 'STARTER', cost: 0, damage: 4, draw: 1, desc: '造成 4 点伤害，抽 1 张牌', vfx: 'physical' },
    { id: 'p3', name: '屏障协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 6, desc: '获得 6 点屏障' },
    { id: 'p3', name: '屏障协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 6, desc: '获得 6 点屏障' },
    { id: 'p3', name: '屏障协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 6, desc: '获得 6 点屏障' },
    { id: 'p3', name: '屏障协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 6, desc: '获得 6 点屏障' },
    { id: 'p4', name: '静电场协议', type: 'POWER', rarity: 'RARE', cost: 2, desc: '每当你打出一张攻击卡，额外造成 3 点伤害', vfx: 'electric' },
    { id: 'p5', name: '十万伏特.bin', type: 'ATTACK', rarity: 'UNCOMMON', cost: 2, damage: 14, desc: '造成 14 点伤害。若 [电荷] >= 3，伤害翻倍', vfx: 'electric' },
    { id: 'p6', name: '充电.sh', type: 'SKILL', rarity: 'COMMON', cost: 1, selfStatusEffect: { type: 'CHARGE', value: 3 }, desc: '获得 3 层 [电荷]' },
    { id: 'p7', name: '雷霆连击.exe', type: 'ATTACK', rarity: 'UNCOMMON', cost: 1, damage: 7, comboValue: 7, desc: '造成 7 点伤害。连击：额外造成 7 点伤害', vfx: 'electric' },
    { id: 'p8', name: '打雷.sys', type: 'ATTACK', rarity: 'RARE', cost: 3, damage: 25, statusEffect: { type: 'FREEZE', value: 1 }, desc: '造成 25 点伤害，施加 1 层 [冻结]', vfx: 'electric' },
    { id: 'p9', name: '电磁波.scan', type: 'SKILL', rarity: 'UNCOMMON', cost: 1, statusEffect: { type: 'WEAK', value: 2 }, desc: '施加 2 层 [虚弱]', vfx: 'electric' },
    { id: 'p10', name: '伏特替换.swap', type: 'ATTACK', rarity: 'RARE', cost: 1, damage: 10, draw: 2, desc: '造成 10 点伤害，抽 2 张牌', vfx: 'electric' },
  ],
  charizard: [
    { id: 'c1', name: '抓取.sh', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害', vfx: 'physical' },
    { id: 'c1', name: '抓取.sh', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害', vfx: 'physical' },
    { id: 'c1', name: '抓取.sh', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害', vfx: 'physical' },
    { id: 'c1', name: '抓取.sh', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害', vfx: 'physical' },
    { id: 'c2', name: '过载喷射.bin', type: 'ATTACK', rarity: 'UNCOMMON', cost: 1, damage: 18, desc: '造成 18 点伤害。获得 2 层 [过载]', vfx: 'fire', selfStatusEffect: { type: 'OVERLOAD', value: 2 } },
    { id: 'c3', name: '热能屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 9, desc: '获得 9 点屏障' },
    { id: 'c3', name: '热能屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 9, desc: '获得 9 点屏障' },
    { id: 'c3', name: '热能屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 9, desc: '获得 9 点屏障' },
    { id: 'c3', name: '热能屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 9, desc: '获得 9 点屏障' },
    { id: 'c4', name: '燃烧协议', type: 'POWER', rarity: 'RARE', cost: 3, desc: '回合结束时，对所有敌人造成 6 点伤害', vfx: 'fire' },
    { id: 'c5', name: '大字爆炎.exe', type: 'ATTACK', rarity: 'RARE', cost: 3, damage: 35, desc: '造成 35 点伤害。消耗', vfx: 'explosion', isExhaust: true },
    { id: 'c6', name: '龙之舞.cmd', type: 'POWER', rarity: 'UNCOMMON', cost: 1, selfStatusEffect: { type: 'STRENGTH', value: 3 }, desc: '获得 3 层 [力量]' },
    { id: 'c7', name: '火焰旋涡.sys', type: 'ATTACK', rarity: 'COMMON', cost: 1, damage: 6, statusEffect: { type: 'BURN', value: 4 }, desc: '造成 6 点伤害，施加 4 层 [灼烧]', vfx: 'fire' },
    { id: 'c8', name: '炼狱.bin', type: 'ATTACK', rarity: 'RARE', cost: 2, damage: 15, statusEffect: { type: 'BURN', value: 10 }, desc: '造成 15 点伤害，施加 10 层 [灼烧]', vfx: 'fire' },
    { id: 'c9', name: '热风.sh', type: 'ATTACK', rarity: 'UNCOMMON', cost: 2, damage: 12, desc: '造成 12 点伤害。对所有敌人施加 2 层 [灼烧]', vfx: 'fire' },
    { id: 'c10', name: '闪焰冲锋.exe', type: 'ATTACK', rarity: 'RARE', cost: 2, damage: 22, selfStatusEffect: { type: 'BURN', value: 2 }, desc: '造成 22 点伤害。对自己施加 2 层 [灼烧]', vfx: 'explosion' },
  ],
  mewtwo: [
    { id: 'm1', name: '念力.py', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, draw: 1, desc: '造成 8 点伤害，抽 1 张牌', vfx: 'psychic' },
    { id: 'm1', name: '念力.py', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, draw: 1, desc: '造成 8 点伤害，抽 1 张牌', vfx: 'psychic' },
    { id: 'm1', name: '念力.py', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, draw: 1, desc: '造成 8 点伤害，抽 1 张牌', vfx: 'psychic' },
    { id: 'm1', name: '念力.py', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 8, draw: 1, desc: '造成 8 点伤害，抽 1 张牌', vfx: 'psychic' },
    { id: 'm2', name: '漏洞扫描.scan', type: 'SKILL', rarity: 'UNCOMMON', cost: 1, statusEffect: { type: 'VULNERABLE', value: 2 }, desc: '施加 2 层 [漏洞暴露]', vfx: 'psychic' },
    { id: 'm3', name: '精神屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'm3', name: '精神屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'm3', name: '精神屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'm3', name: '精神屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'm4', name: '覆写协议', type: 'POWER', rarity: 'RARE', cost: 2, desc: '每当你施加 Debuff，抽 1 张牌', vfx: 'psychic' },
    { id: 'm5', name: '思维干扰.exe', type: 'ATTACK', rarity: 'RARE', cost: 2, damage: 18, statusEffect: { type: 'WEAK', value: 2 }, desc: '造成 18 点伤害，施加 2 层 [虚弱]', vfx: 'psychic' },
    { id: 'm6', name: '精神强念.bin', type: 'ATTACK', rarity: 'RARE', cost: 2, damage: 20, desc: '造成 20 点伤害。每有一张手牌，伤害 +2', vfx: 'psychic' },
  ],
  tyranitar: [
    { id: 't1', name: '咬碎.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'slash' },
    { id: 't1', name: '咬碎.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'slash' },
    { id: 't1', name: '咬碎.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'slash' },
    { id: 't1', name: '咬碎.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'slash' },
    { id: 't2', name: '沙暴.sys', type: 'SKILL', rarity: 'UNCOMMON', cost: 2, shield: 15, desc: '获得 15 点屏障。回合结束时对敌方造成 5 点伤害', vfx: 'rock' },
    { id: 't3', name: '加固协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 't3', name: '加固协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 't3', name: '加固协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 't3', name: '加固协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 't4', name: '硬化协议', type: 'POWER', rarity: 'RARE', cost: 2, desc: '你的屏障在回合结束时不再清零', vfx: 'rock' },
    { id: 't5', name: '岩石封锁.bin', type: 'ATTACK', rarity: 'UNCOMMON', cost: 2, damage: 16, statusEffect: { type: 'WEAK', value: 2 }, desc: '造成 16 点伤害，施加 2 层 [虚弱]', vfx: 'rock' },
    { id: 't6', name: '破坏光线.exe', type: 'ATTACK', rarity: 'RARE', cost: 3, damage: 40, desc: '造成 40 点伤害。下回合失去 1 点算力核心', vfx: 'explosion' },
  ],
  lucario: [
    { id: 'l1', name: '波导弹.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害。必中', vfx: 'psychic' },
    { id: 'l1', name: '波导弹.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害。必中', vfx: 'psychic' },
    { id: 'l1', name: '波导弹.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害。必中', vfx: 'psychic' },
    { id: 'l1', name: '波导弹.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 10, desc: '造成 10 点伤害。必中', vfx: 'psychic' },
    { id: 'l2', name: '增强拳.cmd', type: 'ATTACK', rarity: 'UNCOMMON', cost: 1, damage: 6, selfStatusEffect: { type: 'STRENGTH', value: 2 }, desc: '造成 6 点伤害，获得 2 层 [力量]', vfx: 'physical' },
    { id: 'l3', name: '格挡协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'l3', name: '格挡协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'l3', name: '格挡协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
    { id: 'l3', name: '格挡协议', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 8, desc: '获得 8 点屏障' },
  ],
  gengar: [
    { id: 'g1', name: '暗影球.bin', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'psychic' },
    { id: 'g1', name: '暗影球.bin', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'psychic' },
    { id: 'g1', name: '暗影球.bin', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'psychic' },
    { id: 'g1', name: '暗影球.bin', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 12, desc: '造成 12 点伤害', vfx: 'psychic' },
    { id: 'g2', name: '催眠术.sh', type: 'SKILL', rarity: 'UNCOMMON', cost: 1, statusEffect: { type: 'FREEZE', value: 1 }, desc: '施加 1 层 [冻结]', vfx: 'psychic' },
    { id: 'g3', name: '幽灵屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 7, desc: '获得 7 点屏障' },
    { id: 'g3', name: '幽灵屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 7, desc: '获得 7 点屏障' },
    { id: 'g3', name: '幽灵屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 7, desc: '获得 7 点屏障' },
    { id: 'g3', name: '幽灵屏障', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 7, desc: '获得 7 点屏障' },
  ],
  dragonite: [
    { id: 'd1', name: '龙爪.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 14, desc: '造成 14 点伤害', vfx: 'physical' },
    { id: 'd1', name: '龙爪.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 14, desc: '造成 14 点伤害', vfx: 'physical' },
    { id: 'd1', name: '龙爪.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 14, desc: '造成 14 点伤害', vfx: 'physical' },
    { id: 'd1', name: '龙爪.exe', type: 'ATTACK', rarity: 'STARTER', cost: 1, damage: 14, desc: '造成 14 点伤害', vfx: 'physical' },
    { id: 'd2', name: '逆鳞.bin', type: 'ATTACK', rarity: 'RARE', cost: 2, damage: 24, selfStatusEffect: { type: 'STRENGTH', value: 5 }, desc: '造成 24 点伤害，获得 5 层 [力量]', vfx: 'fire' },
    { id: 'd3', name: '龙之鳞片', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 10, desc: '获得 10 点屏障' },
    { id: 'd3', name: '龙之鳞片', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 10, desc: '获得 10 点屏障' },
    { id: 'd3', name: '龙之鳞片', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 10, desc: '获得 10 点屏障' },
    { id: 'd3', name: '龙之鳞片', type: 'SKILL', rarity: 'STARTER', cost: 1, shield: 10, desc: '获得 10 点屏障' },
  ]
};

export const RELICS_DB: Relic[] = [
  { id: 'usb', name: '生锈的U盘', desc: '每场战斗第一回合额外抽 2 张牌', icon: 'Database', price: 140 },
  { id: 'cooling', name: '液冷系统', desc: '每次洗牌时恢复 5 点系统完整度', icon: 'Activity', price: 160 },
  { id: 'battery', name: '备用电池', desc: '每回合开始时额外获得 1 点算力核心', icon: 'Zap', price: 240 },
  { id: 'shield_gen', name: '便携护盾发生器', desc: '每场战斗开始时获得 10 点屏障', icon: 'Shield', price: 110 },
  { id: 'chip', name: '超频芯片', desc: '你的攻击额外造成 1 点伤害', icon: 'Swords', price: 180 },
  { id: 'gold_magnet', name: '金币磁铁', desc: '每场战斗额外获得 10 金币', icon: 'Coins', price: 130 },
  { id: 'heal_module', name: '修复模块', desc: '战斗胜利后恢复 10% 系统完整度', icon: 'HeartPulse', price: 200 },
  { id: 'energy_core', name: '能量核心', desc: '最大算力核心 +1', icon: 'Zap', price: 280 },
  { id: 'data_analyzer', name: '数据分析仪', desc: '战斗奖励中额外出现 1 张卡牌选项', icon: 'Search', price: 160 },
  { id: 'exp_share', name: '学习装置', desc: '战斗胜利后金币奖励增加 25%', icon: 'Share2', price: 150 },
  { id: 'quick_claw', name: '先制之爪', desc: '每场战斗第一张攻击牌伤害翻倍', icon: 'Zap', price: 220 },
  { id: 'focus_band', name: '气势披带', desc: '每场战斗可抵挡一次致命伤害，保留 1 点生命', icon: 'Heart', price: 250 },
  { id: 'leftovers', name: '吃剩的东西', desc: '回合结束时恢复 2 点生命', icon: 'Coffee', price: 180 },
  { id: 'rocky_helmet', name: '凸凸头盔', desc: '受到攻击时对敌方造成 3 点反伤', icon: 'ShieldAlert', price: 160 },
];

export const CONSUMABLES_DB: Consumable[] = [
  { id: 'potion', name: '伤药 (Potion)', desc: '恢复 20 点系统完整度', icon: 'Heart', price: 40, type: 'HEAL', value: 20 },
  { id: 'super_potion', name: '好伤药 (Super Potion)', desc: '恢复 50 点系统完整度', icon: 'HeartPulse', price: 85, type: 'HEAL', value: 50 },
  { id: 'hyper_potion', name: '厉害伤药 (Hyper Potion)', desc: '恢复 120 点系统完整度', icon: 'Activity', price: 160, type: 'HEAL', value: 120 },
  { id: 'max_potion', name: '全满药 (Max Potion)', desc: '恢复全部系统完整度', icon: 'Zap', price: 280, type: 'HEAL', value: 999 },
  { id: 'ether', name: '能量补给 (Ether)', desc: '获得 2 点算力核心', icon: 'Zap', price: 60, type: 'ENERGY', value: 2 },
  { id: 'max_ether', name: '全满能量 (Max Ether)', desc: '获得 5 点算力核心', icon: 'Zap', price: 120, type: 'ENERGY', value: 5 },
  { id: 'full_heal', name: '万灵药 (Full Heal)', desc: '清除所有负面状态', icon: 'RefreshCw', price: 90, type: 'STATUS', value: 0 },
  { id: 'x_attack', name: '力量强化 (X Attack)', desc: '获得 3 层 [力量]', icon: 'Swords', price: 75, type: 'STATUS', statusType: 'STRENGTH', value: 3 },
  { id: 'x_defense', name: '防御强化 (X Defense)', desc: '获得 3 层 [敏捷]', icon: 'Shield', price: 75, type: 'STATUS', statusType: 'DEXTERITY', value: 3 },
  { id: 'x_speed', name: '速度强化 (X Speed)', desc: '抽 2 张牌', icon: 'Zap', price: 50, type: 'DRAW', value: 2 },
  { id: 'x_accuracy', name: '命中强化 (X Accuracy)', desc: '获得 2 层 [电荷]', icon: 'Crosshair', price: 60, type: 'STATUS', statusType: 'CHARGE', value: 2 },
  { id: 'guard_spec', name: '能力防守 (Guard Spec.)', desc: '获得 5 点屏障', icon: 'ShieldCheck', price: 45, type: 'STATUS', value: 5 },
  { id: 'rare_candy', name: '神奇糖果 (Rare Candy)', desc: '最大系统完整度 +20', icon: 'Star', price: 150, type: 'STATUS', value: 20 },
  { id: 'poke_ball', name: '精灵球 (Poke Ball)', desc: '尝试捕获敌方。生命值越低成功率越高。', icon: 'Circle', price: 80, type: 'STATUS', value: 0 },
  { id: 'great_ball', name: '超级球 (Great Ball)', desc: '更高成功率捕获敌方。', icon: 'Circle', price: 150, type: 'STATUS', value: 10 },
  { id: 'ultra_ball', name: '高级球 (Ultra Ball)', desc: '极高成功率捕获敌方。', icon: 'Circle', price: 300, type: 'STATUS', value: 25 },
  { id: 'master_ball', name: '大师球 (Master Ball)', desc: '必定捕获非Boss敌方。', icon: 'Disc', price: 500, type: 'STATUS', value: 100 },
  { id: 'revive', name: '复活药 (Revive)', desc: '复活一名已宕机的宝可梦并恢复 50% HP。', icon: 'Zap', price: 200, type: 'STATUS', value: 50 },
  { id: 'max_revive', name: '全复活药 (Max Revive)', desc: '复活一名已宕机的宝可梦并恢复全部 HP。', icon: 'Zap', price: 400, type: 'STATUS', value: 100 },
  { id: 'dire_hit', name: '致命攻击 (Dire Hit)', desc: '下一次攻击伤害翻倍。', icon: 'Crosshair', price: 100, type: 'STATUS', value: 2 },
  { id: 'iron', name: '铁壁 (Iron)', desc: '永久提升 5 点初始屏障。', icon: 'ShieldCheck', price: 180, type: 'STATUS', value: 5 },
  { id: 'protein', name: '力量上升 (Protein)', desc: '永久提升 2 点最大 HP。', icon: 'Swords', price: 120, type: 'STATUS', value: 2 },
];

export const SHOP_UPGRADES_DB: ShopUpgrade[] = [
  { id: 'bulk_discount', name: '大宗采购协议', desc: '商店所有商品价格永久降低 15%', icon: 'ShoppingCart', price: 250, effect: 'DISCOUNT' },
  { id: 'data_miner', name: '数据挖掘工具', desc: '刷新商店的费用降低 50%', icon: 'Search', price: 180, effect: 'REFRESH_SALE' },
  { id: 'lucky_charm', name: '幸运护符', desc: '抽奖获得稀有奖励的概率提升', icon: 'Star', price: 220, effect: 'GACHA_LUCK' },
  { id: 'premium_access', name: '高级访问权限', desc: '商店中出现稀有协议的概率提升', icon: 'Lock', price: 300, effect: 'RARE_CHANCE' },
];

export const TASKS_DB: Task[] = [
  { id: 'daily_login', title: '每日签到', desc: '今天也要努力渗透网络', reward: 50, type: 'DAILY_LOGIN', progress: 0, target: 1, isClaimed: false },
  { id: 'battle_win_1', title: '初露锋芒', desc: '赢得 1 场战斗', reward: 30, type: 'BATTLE_WIN', progress: 0, target: 1, isClaimed: false },
  { id: 'battle_win_3', title: '渗透专家', desc: '赢得 3 场战斗', reward: 100, type: 'BATTLE_WIN', progress: 0, target: 3, isClaimed: false },
  { id: 'gold_spent_100', title: '消费达人', desc: '在商店消费 100 金币', reward: 50, type: 'GOLD_SPENT', progress: 0, target: 100, isClaimed: false },
];

export const ENEMIES_DB = [
  // Normal Enemies
  { id: 'rattata', name: '小拉达.virus', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png', maxHp: 45, color: '#a8a878', neonClass: 'neon-gray', bgGradient: 'from-gray-900/40 to-black' },
  { id: 'caterpie', name: '绿毛虫.worm', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', maxHp: 40, color: '#a8b820', neonClass: 'neon-green', bgGradient: 'from-green-900/40 to-black' },
  { id: 'pidgey', name: '波波.bot', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', maxHp: 50, color: '#a890f0', neonClass: 'neon-blue', bgGradient: 'from-blue-900/40 to-black' },
  { id: 'zubat', name: '超音蝠.sonar', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png', maxHp: 55, color: '#a040a0', neonClass: 'neon-purple', bgGradient: 'from-purple-900/40 to-black' },
  { id: 'meowth', name: '喵喵.coin', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png', maxHp: 65, color: '#f7d02c', neonClass: 'neon-yellow', bgGradient: 'from-yellow-900/40 to-black' },
  { id: 'gastly', name: '鬼斯.ghost', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png', maxHp: 60, color: '#705898', neonClass: 'neon-purple', bgGradient: 'from-purple-900/40 to-black' },
  { id: 'magnemite', name: '小磁怪.magnet', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png', maxHp: 70, color: '#b8b8d0', neonClass: 'neon-gray', bgGradient: 'from-gray-900/40 to-black' },
  { id: 'koffing', name: '瓦斯弹.gas', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', maxHp: 75, color: '#a040a0', neonClass: 'neon-purple', bgGradient: 'from-purple-900/40 to-black' },
  { id: 'machop', name: '腕力.str', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png', maxHp: 80, color: '#d0d0d0', neonClass: 'neon-gray', bgGradient: 'from-gray-900/40 to-black' },
  { id: 'abra', name: '凯西.teleport', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png', maxHp: 40, color: '#f8d030', neonClass: 'neon-yellow', bgGradient: 'from-yellow-900/40 to-black' },
  { id: 'geodude', name: '小拳石.rock', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png', maxHp: 90, color: '#b8b8d0', neonClass: 'neon-gray', bgGradient: 'from-gray-900/40 to-black' },
  
  // Elite Enemies
  { id: 'scyther', name: '飞天螳螂.blade', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png', maxHp: 120, color: '#a8b820', neonClass: 'neon-green', bgGradient: 'from-green-900/40 to-black', isElite: true },
  { id: 'gyarados', name: '暴鲤龙.hydra', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', maxHp: 150, color: '#7038f8', neonClass: 'neon-blue', bgGradient: 'from-blue-900/40 to-black', isElite: true },
  { id: 'gengar_elite', name: '耿鬼.phantom', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', maxHp: 140, color: '#705898', neonClass: 'neon-purple', bgGradient: 'from-purple-900/40 to-black', isElite: true },
  { id: 'alakazam', name: '胡地.mind', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png', maxHp: 130, color: '#f8d030', neonClass: 'neon-yellow', bgGradient: 'from-yellow-900/40 to-black', isElite: true },
  { id: 'machamp', name: '怪力.titan', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png', maxHp: 180, color: '#d0d0d0', neonClass: 'neon-gray', bgGradient: 'from-gray-900/40 to-black', isElite: true },

  // Bosses
  { id: 'articuno', name: '急冻鸟.cryo', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png', maxHp: 300, color: '#98d8d8', neonClass: 'neon-blue', bgGradient: 'from-blue-900/40 to-black', isBoss: true },
  { id: 'zapdos', name: '闪电鸟.volt', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png', maxHp: 300, color: '#f8d030', neonClass: 'neon-yellow', bgGradient: 'from-yellow-900/40 to-black', isBoss: true },
  { id: 'moltres', name: '火焰鸟.pyro', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png', maxHp: 300, color: '#f08030', neonClass: 'neon-orange', bgGradient: 'from-orange-900/40 to-black', isBoss: true },
  { id: 'dragonite_boss', name: '快龙.dragon', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', maxHp: 400, color: '#7038f8', neonClass: 'neon-orange', bgGradient: 'from-orange-900/40 to-black', isBoss: true },
  { id: 'mewtwo_boss', name: '超梦.omega', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png', maxHp: 600, color: '#c084fc', neonClass: 'neon-purple', bgGradient: 'from-purple-900/40 to-black', isBoss: true },
  { id: 'rayquaza', name: '烈空坐.zenith', img: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png', maxHp: 800, color: '#4ade80', neonClass: 'neon-green', bgGradient: 'from-green-900/40 to-black', isBoss: true },
];

export const JUNK_CARD: Omit<Card, 'uid'> = {
  id: 'junk',
  name: '垃圾数据 (Junk)',
  type: 'SKILL',
  rarity: 'SPECIAL',
  cost: 1,
  desc: '消耗 1 点能量以清理。回合结束时，若在手牌中，失去 2 点系统完整度。',
  vfx: 'glitch',
  isExhaust: true,
};

export const CARDS_DB: Omit<Card, 'uid'>[] = Array.from(
  new Set(Object.values(INITIAL_DECKS).flat().map(c => JSON.stringify(c)))
).map(s => JSON.parse(s));
